export const ROUTES = {
  ADMIN: {
    SIDEBAR: {
      DASHBOARD: "/admin",
      ADMINS: "/admin/admin-management",
      ROLES: "/admin/roles",
      PERMISSIONS: "/admin/permissions",
      CUSTOMERS: "/admin/customers",
      PRODUCTS: "/admin/products",
      ORDERS: "/admin/orders",
      MANUFACTURERS: "/admin/manufacturers",
      REPORTS: "/admin/reports",
      STOREMANAGEMENT: "/admin/store-management",
      INVEMTORYMANAGEMENT: "/admin/inventory-management",
      FINANCIALREPORTS: "/admin/financial-reports",
      TRANSACTIONMANAGEMENT: "/admin/transaction-management",
      NOTIFICATIONS: "/admin/notifications",
      SETTINGS: "/admin/settings",
      SUPPLYMANAGEMENTMANUFACTURERS: "/admin/supply-management/manufacturers",
      SUPPLYMANAGEMENTVENDORS: "/admin/supply-management/vendors",
      FEEDBACK: "/admin/feedback",
      SUPPORT: "/admin/support",
    },
  },
};
